### ISSUE TITLE
Perubahan Endpoint

### ISSUE THREAD

**Issue by bionyxxx** [swiftalker/tripay-payment-gateway#10]
halo gan, saya cek buat endpointnya sudah tidak sama dengan yg di dokumentasi tripay skrng kaya GetChannelPembayaran 

library : https://tripay.co.id/api-sandbox/payment/channel

tripay : https://tripay.co.id/api-sandbox/merchant/payment-channel

jdi kalo berkenan mngkin agan bisa update ke lebih terbaru ya gan..

terimakasih

**Comment by swiftalker** [comment]
perlu diketahui package ini memiliki **Merchant Channel Pembayaran** dan **Channel Pembayaran**, silahkan dilihat kembali kepada dokumentasi untuk paket yang anda butuhkan..
